# =================================================================
# playing with Lemon, the SQLite parser
# =================================================================

CC = clang
LD = clang

all: lemon

lemon: lemon.c
	$(CC) -O2 -o $@ $<



